title: Streamdata Gallery Azure Service Fabric
url: azure-service-fabric.streamdata.gallery
tag: Azure Service Fabric
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: azure-service-fabric
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
